// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozzdjeduhharegdketgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96emRqZWR1aGhhcmVnZGtldGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjYzNDUsImV4cCI6MjA3MDgwMjM0NX0.xG1BDSorWjnncXfOGfthrBMaoHYhQCUkdtg076mpWvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});